version: "3"

services:
  job_application_db:
    image: postgres:latest
    container_name: job_application_db
    ports:
      - "5436:5432"
    environment:
      POSTGRES_USER: $DB_USER
      POSTGRES_PASSWORD: $DB_PASSWORD
      POSTGRES_DB: $DB_NAME
    restart: always
    volumes:
      - job_application_database:/var/lib/postgresql/data/

  job_application_api:
    build:
      context: ./api
      dockerfile: Dockerfile
    command: >
      sh -c "python -m manage migrate && python -m manage collectstatic && 
             gunicorn config.wsgi:application --bind 0.0.0.0:8000"
    image: job_application:latest
    container_name: job_application_api
    depends_on:
      - job_application_db
    restart: on-failure
    ports:
      - "9046:8000"

volumes:
  job_application_database: